---
layout: post
title: Why publish open source when you are commercial?
date: '2014-03-08T19:07:00.000Z'
author: Tim Abell
tags: 
modified_time: '2014-03-08T19:07:01.451Z'
blogger_id: tag:blogger.com,1999:blog-5082828566240519947.post-5055561057000769363
blogger_orig_url: https://timwise.blogspot.com/2014/03/why-publish-open-source-when-you-are.html
---

Why open source your commercial projects?<br /><ul><li dir="ltr">Forces you to decouple them from other internal systems.</li><li dir="ltr">Encourages thinking in terms of reusable modules, which is better for internal reuse just as much as public reuse.</li><li dir="ltr">Possibility of contributions to systems useful to your business by others.</li><li dir="ltr">Easier reuse within your organisation (the public internet is a better search and sharing system than any internal systems).</li><li dir="ltr">Reputation advantages, the best coders often like to work in open and forward-thinking companies, and having public shared code is a great sign of such an organisation.</li></ul>Do it early<br /><ul><li dir="ltr">Preferably push your very first commit straight to github.</li><li dir="ltr">Do it before it has a chance to be tightly coupled to internal systems, otherwise you'll have to unpick it and it will be less decoupled from day one, and inertia might mean that in spite of the best intentions you then never publish it.</li><li dir="ltr">You'll have it in mind that every commit is public from day one, avoiding adding internal config etc and forcing you to factor it out into config which is all round a good thing.</li><li dir="ltr">Don't wait for your code to be perfect, there are compromises in all code and sharing something imperfect is better than sharing nothing.</li></ul><div class="separator" style="clear: both; text-align: center;"><a href="https://secure.flickr.com/photos/tim_abell/12293521763/"><img border="0" src="https://farm4.staticflickr.com/3756/12293521763_bfebeeaa41_n.jpg" /></a></div><div><br /></div><div>Worried about the brand?</div><ul><li dir="ltr">Commit under personal email addresses and push to personal github accounts. You can always setup a corporate github account later when you are feeling more confident.</li></ul><br />Of course I'm not saying you should open source everything, for example your core product's codebase should probably not go on github if you are a product company!<br /><br />--<br /><br /><i>Be brave, be open.</i><br />Props to <a href="https://twitter.com/tomskitomski">Tom Loosemoore</a>