---
layout: post
title: Converting kml to gpx with python
date: '2014-02-03T20:27:00.000Z'
author: Tim Abell
tags: 
modified_time: '2014-02-03T20:29:19.425Z'
blogger_id: tag:blogger.com,1999:blog-5082828566240519947.post-6598892897913494731
blogger_orig_url: https://timwise.blogspot.com/2014/02/converting-kml-to-gpx-with-python.html
---

Today I wanted to geo-code some of my photos.<br /><br />I have an SLR digital camera (no gps of course), and an android phone. I recorded a track with <a href="https://play.google.com/store/apps/details?id=com.google.android.maps.mytracks">My Tracks</a> from google on the phone. (Not entirely recommended but works). I then fired up digikam to run the geo-correlation and add lat-long to the exif of the files only to discover <a href="http://community.kde.org/Digikam/GSoC2010/ReverseGeocoding#TODO_Later_versions">digikam doesn't know how to read kml</a>. Fooey.<br /><br /><div style="text-align: center;"><a href="https://secure.flickr.com/photos/tim_abell/12293521763/" target="_blank"><img alt="" src="https://farm4.staticflickr.com/3756/12293521763_bfebeeaa41_n.jpg" /></a>&nbsp;</div><br />I looked to gpsbabel, but it apparently can't handle this style of kml file, as differentiated by the coordinates being in the following style of markup:<br /><br /><code>&lt;gx:Track&gt;<br />&lt;when&gt;2014-01-25T18:00:13.955Z&lt;/when&gt;<br />&lt;gx:coord&gt;-1.885348 50.769434&lt;/gx:coord&gt;<br />&lt;when&gt;2014-01-25T18:00:14.565Z&lt;/when&gt;<br />&lt;gx:coord&gt;-1.885193 50.769328 53.20000076293945&lt;/gx:coord&gt;<br />&lt;when&gt;2014-01-25T18:00:58.566Z&lt;/when&gt;</code><br /><div><br />So I wrote a python script to munge it into gpx shape:</div><div><br /></div><div class="gistLoad" data-id="8791116" id="gist-GistID"><a href="https://gist.github.com/timabell/8791116" target="_blank">https://gist.github.com/timabell/8791116</a><br /><br />This can be run as follows:<br /><br /><code>./kmlToGpx.py "25-01 12-48.kml" &gt; "25-01 12-48.kml.gpx"</code><br /><br />And worked a treat for me.<br /><br />After I'd done this I discovered my pet tool <a href="http://activityworkshop.net/software/gpsprune/index.html">gpsprune</a> can open the new style kml. (I <a href="https://github.com/timabell/gpsprune">forked gpsprune</a> a while ago and added a minor feature) However I'm glad to have a command-line tool as I have hundreds of tracks I want to convert.<br /><br />Incidentally the phone can automatically sync the tracks to google drive, which is kinda handy and then you can download them from the site etc.<br /><div><br /></div></div>